services:
  database:
    image: postgres:16
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: todo
    ports:
      - "5432:5432"
    container_name: todo_test_pg